name: Publish Docs Workflow
run-name: ${{ github.actor }} is running GitHub Actions ğŸš€
on: [push]
jobs:
  Publish Docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: make html
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/_build/html

      - name: Rsync HTML
          uses: llpeterson/rsync-deploy-action@v1.0.0
          id: rsync-deploy-action
          with:
            ssh_login_username: ${{ secrets.SSH_LOGIN_USERNAME }}
            remote_server_ip: ${{ secrets.REMOTE_SERVER_IP }}
            ssh_port: ${{ secrets.SSH_PORT }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            source_path: ${{ github.workspace }}/_build/html
            destination_path: ~/rsync_test

      - run: echo "ğŸ This job's status is ${{ job.status }}."
