name: Publish Docs Workflow
run-name: ${{ github.actor }} is publishing document artifacts ğŸš€
on: [push, workflow_dispatch]
jobs:
  Publish_Docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build html
        run: make html
      - name: List built files
        run: |
          ls ${{ github.workspace }}/_build/html

      - run: chmod +x ./.github/scripts/rsync.sh
      - name: rsync html
        env:
          ssh_login_username: ${{ secrets.SSH_LOGIN_USERNAME }}
          remote_server_ip: ${{ secrets.REMOTE_SERVER_IP }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          src_path: ${{ github.workspace }}/_build/html
          dst_path: ~/rsync_test
	run: echo ssh_login_username remote_server_ip ssh_port src_path dst_path

      - run: echo "ğŸ This job's status is ${{ job.status }}."
